formats:
  - oas3
  - oas2
extends:
  - 'spectral:oas'
rules:
  info-matches-stoplight:
    description: This is an example rule
    message: Info must contain Stoplight
    given: $.info
    recommended: true
    type: style
    then:
      field: title
      function: pattern
      functionOptions:
        match: Stoplight
    severity: 'off'
  contact-properties: error
  info-contact: error
  info-license: warn
  license-url: error
  oas3-schema: info
  oas3-valid-schema-example: error
  oas3-valid-media-example: error
  oas3-examples-value-or-externalValue: error
  oas2-oneOf: error
  oas2-valid-media-example: error
  oas2-valid-schema-example: error
  operation-singular-tag: 'off'
  operation-operationId: error
  oas2-parameter-description: error
  tag-description: error
